/**
 * Production city catalog by Indian state / UT.
 * Capitals + major delivery markets (Swiggy/Zomato-scale coverage).
 */
export const CITIES_BY_STATE: Record<string, readonly string[]> = {
  'Andaman and Nicobar Islands': ['Port Blair', 'Havelock Island', 'Diglipur'],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Anantapur',
    'Eluru',
    'Ongole',
    'Kadapa',
    'Chittoor',
    'Srikakulam',
    'Vizianagaram',
    'Machilipatnam',
    'Tenali',
    'Proddatur',
    'Hindupur',
    'Bhimavaram',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Naharlagun',
    'Tawang',
    'Pasighat',
    'Ziro',
    'Bomdila',
    'Tezu',
  ],
  Assam: [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Karimganj',
    'Sivasagar',
    'Goalpara',
    'Barpeta',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Bihar Sharif',
    'Arrah',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chhapra',
    'Danapur',
    'Sasaram',
    'Hajipur',
    'Dehri',
    'Siwan',
    'Motihari',
    'Nawada',
  ],
  Chandigarh: ['Chandigarh'],
  Chhattisgarh: [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Durg',
    'Rajnandgaon',
    'Raigarh',
    'Jagdalpur',
    'Ambikapur',
    'Dhamtari',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Daman',
    'Diu',
    'Silvassa',
  ],
  Delhi: [
    'New Delhi',
    'Delhi',
    'North Delhi',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'Central Delhi',
    'Dwarka',
    'Rohini',
    'Saket',
    'Karol Bagh',
    'Connaught Place',
    'Laxmi Nagar',
    'Mayur Vihar',
    'Vasant Kunj',
    'Janakpuri',
  ],
  Goa: [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Calangute',
    'Candolim',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Nadiad',
    'Morbi',
    'Mehsana',
    'Bharuch',
    'Vapi',
    'Navsari',
    'Surendranagar',
    'Gandhidham',
    'Veraval',
    'Porbandar',
    'Godhra',
  ],
  Haryana: [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Bhiwani',
    'Sirsa',
    'Bahadurgarh',
    'Jind',
    'Thanesar',
    'Kaithal',
    'Rewari',
    'Palwal',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Dharamshala',
    'Solan',
    'Mandi',
    'Palampur',
    'Kullu',
    'Manali',
    'Baddi',
    'Nahan',
    'Una',
    'Hamirpur',
    'Bilaspur',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Sopore',
    'Kathua',
    'Udhampur',
    'Punch',
    'Rajouri',
  ],
  Jharkhand: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro Steel City',
    'Deoghar',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    'Phusro',
    'Medininagar',
    'Chaibasa',
  ],
  Karnataka: [
    'Bengaluru',
    'Mysuru',
    'Mangaluru',
    'Hubballi',
    'Belagavi',
    'Kalaburagi',
    'Ballari',
    'Davangere',
    'Shivamogga',
    'Tumakuru',
    'Raichur',
    'Bidar',
    'Hosapete',
    'Udupi',
    'Vijayapura',
    'Hassan',
    'Chikkamagaluru',
    'Mandya',
    'Chitradurga',
    'Kolar',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Alappuzha',
    'Kannur',
    'Kottayam',
    'Palakkad',
    'Malappuram',
    'Manjeri',
    'Thalassery',
    'Ponnani',
    'Vadakara',
    'Kanhangad',
  ],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Kavaratti', 'Agatti'],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
    'Murwara',
    'Singrauli',
    'Burhanpur',
    'Khandwa',
    'Morena',
    'Bhind',
    'Chhindwara',
    'Guna',
    'Shivpuri',
    'Vidisha',
    'Damoh',
    'Mandsaur',
    'Khargone',
    'Neemuch',
    'Pithampur',
    'Tikamgarh',
    'Hoshangabad',
    'Itarsi',
    'Sehore',
    'Betul',
  ],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Amravati',
    'Navi Mumbai',
    'Kolhapur',
    'Sangli',
    'Jalgaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Chandrapur',
    'Parbhani',
    'Ichalkaranji',
    'Jalna',
    'Bhiwandi',
    'Panvel',
    'Satara',
    'Beed',
    'Yavatmal',
    'Kamptee',
    'Gondia',
    'Barshi',
    'Achalpur',
    'Osmanabad',
    'Nanded',
    'Wardha',
    'Udgir',
    'Hinganghat',
  ],
  Manipur: ['Imphal', 'Thoubal', 'Bishnupur', 'Churachandpur', 'Ukhrul'],
  Meghalaya: ['Shillong', 'Tura', 'Nongpoh', 'Jowai', 'Baghmara'],
  Mizoram: ['Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Kolasib'],
  Nagaland: ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha'],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
    'Jeypore',
    'Bargarh',
    'Rayagada',
    'Balangir',
  ],
  Puducherry: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
  Punjab: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Hoshiarpur',
    'Batala',
    'Pathankot',
    'Moga',
    'Abohar',
    'Malerkotla',
    'Khanna',
    'Phagwara',
    'Muktsar',
    'Barnala',
    'Rajpura',
    'Firozpur',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
    'Sri Ganganagar',
    'Kishangarh',
    'Beawar',
    'Tonk',
    'Churu',
    'Jhunjhunu',
    'Sawai Madhopur',
    'Hanumangarh',
    'Dausa',
  ],
  Sikkim: ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan', 'Rangpo'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Thoothukudi',
    'Dindigul',
    'Thanjavur',
    'Ranipet',
    'Sivakasi',
    'Karur',
    'Udhagamandalam',
    'Hosur',
    'Nagercoil',
    'Kanchipuram',
    'Kumbakonam',
    'Cuddalore',
    'Neyveli',
    'Nagapattinam',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Khammam',
    'Karimnagar',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Miryalaguda',
    'Siddipet',
    'Jagtial',
  ],
  Tripura: ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar', 'Belonia'],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Ghaziabad',
    'Agra',
    'Varanasi',
    'Meerut',
    'Prayagraj',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Noida',
    'Greater Noida',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Ayodhya',
    'Rampur',
    'Shahjahanpur',
    'Farrukhabad',
    'Maunath Bhanjan',
    'Hapur',
    'Etawah',
    'Mirzapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Hardoi',
    'Fatehpur',
    'Raebareli',
    'Orai',
    'Sitapur',
    'Bahraich',
    'Modinagar',
    'Unnao',
    'Jaunpur',
    'Lakhimpur',
    'Hathras',
    'Banda',
    'Pilibhit',
    'Barabanki',
    'Khurja',
    'Gonda',
    'Mainpuri',
    'Lalitpur',
    'Etah',
    'Deoria',
    'Basti',
    'Ghazipur',
    'Sultanpur',
    'Azamgarh',
    'Bijnor',
    'Sahibabad',
    'Dadri',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Nainital',
    'Mussoorie',
    'Almora',
    'Pithoragarh',
    'Kotdwar',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Shantipur',
    'Dankuni',
    'Dhulian',
    'Ranaghat',
    'Haldia',
    'Raiganj',
    'Krishnanagar',
    'Nabadwip',
    'Medinipur',
    'Jalpaiguri',
    'Balurghat',
    'Bankura',
    'Cooch Behar',
    'Alipurduar',
    'Purulia',
  ],
};
