import { StyleSheet } from 'react-native';

import { authTheme } from '@/constants/auth-theme';
import { fonts } from '@/constants/typography';

export const earningsPageStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F6F3F0' },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 4,
    gap: 12,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  title: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  sub: {
    marginTop: 6,
    marginBottom: 12,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  scroll: { paddingHorizontal: 16, gap: 12 },
  segment: {
    flexDirection: 'row',
    backgroundColor: '#EAE3DD',
    borderRadius: 14,
    padding: 3,
  },
  segmentBtn: {
    flex: 1,
    minHeight: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentOn: { backgroundColor: '#FFFFFF' },
  segmentText: { fontFamily: fonts.medium, fontSize: 12, color: '#64748B' },
  segmentTextOn: { fontFamily: fonts.bold, color: authTheme.brand },
  center: { paddingVertical: 48, alignItems: 'center', gap: 8 },
  muted: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
    lineHeight: 18,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EFE6DF',
    padding: 16,
    gap: 8,
  },
  cardTitle: { fontFamily: fonts.bold, fontSize: 15, color: '#0F172A' },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  link: { fontFamily: fonts.bold, fontSize: 13, color: authTheme.brand },
  pair: { flexDirection: 'row', gap: 10 },
  pairCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EFE6DF',
    padding: 14,
    gap: 8,
  },
  kicker: {
    fontFamily: fonts.semiBold,
    fontSize: 11,
    color: '#94A3B8',
    letterSpacing: 0.4,
  },
  pairAmount: {
    fontFamily: fonts.extraBold,
    fontSize: 22,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  primaryBtn: {
    marginTop: 4,
    minHeight: 36,
    borderRadius: 12,
    backgroundColor: authTheme.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: { fontFamily: fonts.bold, fontSize: 13, color: '#FFFFFF' },
  ghostBtn: {
    marginTop: 4,
    minHeight: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FDBA74',
    backgroundColor: '#FFF7F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostBtnText: { fontFamily: fonts.bold, fontSize: 13, color: authTheme.brand },
  actions: { flexDirection: 'row', gap: 8 },
  action: {
    flex: 1,
    minHeight: 64,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EFE6DF',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  actionText: { fontFamily: fonts.medium, fontSize: 12, color: '#0F172A' },
  warn: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#FFF7ED',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FDBA74',
    padding: 14,
  },
  warnText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#9A3412',
    lineHeight: 18,
  },
  heroAmount: {
    fontFamily: fonts.extraBold,
    fontSize: 32,
    color: '#0F172A',
    letterSpacing: -0.6,
  },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  cell: {
    width: '50%',
    paddingVertical: 12,
    paddingRight: 8,
    gap: 2,
  },
  cellValue: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: '#0F172A',
  },
  cellLabel: { fontFamily: fonts.medium, fontSize: 12, color: '#64748B' },
  negative: { color: '#B91C1C' },
  row: {
    paddingVertical: 12,
    gap: 4,
    borderTopWidth: 1,
    borderTopColor: '#F1EAE3',
  },
  rowTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  rowTitle: {
    flex: 1,
    fontFamily: fonts.semiBold,
    fontSize: 14,
    color: '#0F172A',
  },
  rowValue: { fontFamily: fonts.bold, fontSize: 14, color: '#0F172A' },
  rowMeta: { fontFamily: fonts.medium, fontSize: 12, color: '#64748B', lineHeight: 17 },
  badge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeOk: { backgroundColor: '#DCFCE7' },
  badgeWait: { backgroundColor: '#FEF3C7' },
  badgeText: { fontFamily: fonts.semiBold, fontSize: 11 },
  badgeTextOk: { color: '#15803D' },
  badgeTextWait: { color: '#B45309' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F6F3F0',
  },
  chipOn: { backgroundColor: '#FFF1E8' },
  chipText: { fontFamily: fonts.medium, fontSize: 12, color: '#64748B' },
  chipTextOn: { fontFamily: fonts.bold, color: authTheme.brand },
  track: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F6F3F0',
    overflow: 'hidden',
  },
  fill: { height: '100%', borderRadius: 3, backgroundColor: authTheme.brand },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between' },
  retry: {
    alignSelf: 'flex-start',
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: authTheme.brand,
  },
  retryText: { fontFamily: fonts.semiBold, fontSize: 13, color: '#FFFFFF' },
  empty: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#94A3B8',
    paddingVertical: 8,
  },
});
