import { StyleSheet } from 'react-native';

import { authTheme } from '@/constants/auth-theme';
import { fonts } from '@/constants/typography';

export const analyticsPageStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F6F3F0' },
  header: { paddingHorizontal: 20, paddingBottom: 4 },
  title: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  sub: {
    marginTop: 2,
    marginBottom: 14,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  scroll: { paddingHorizontal: 16, gap: 12 },
  center: { paddingVertical: 48, alignItems: 'center', gap: 10 },
  errorText: {
    fontFamily: fonts.medium,
    fontSize: 14,
    color: '#B91C1C',
    textAlign: 'center',
  },
  retry: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: authTheme.brand,
  },
  retryText: { fontFamily: fonts.semiBold, fontSize: 13, color: '#FFFFFF' },
  hero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EFE6DF',
    overflow: 'hidden',
  },
  controls: { gap: 10 },
  segment: {
    flexDirection: 'row',
    backgroundColor: '#EAE3DD',
    borderRadius: 14,
    padding: 3,
  },
  segmentBtn: {
    flex: 1,
    minHeight: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentOn: { backgroundColor: '#FFFFFF' },
  segmentText: { fontFamily: fonts.medium, fontSize: 13, color: '#64748B' },
  segmentTextOn: { fontFamily: fonts.bold, color: authTheme.brand },
  rangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EFE6DF',
  },
  rangeRule: { width: 1, alignSelf: 'stretch', backgroundColor: '#F1EAE3' },
  dateField: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 2,
  },
  dateLabel: { fontFamily: fonts.medium, fontSize: 11, color: '#94A3B8' },
  dateBtn: { minHeight: 28, justifyContent: 'center' },
  dateValue: { fontFamily: fonts.bold, fontSize: 14, color: '#0F172A' },
  heroBody: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 4 },
  heroKicker: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#94A3B8',
    letterSpacing: 0.4,
  },
  heroAmount: {
    marginTop: 4,
    fontFamily: fonts.extraBold,
    fontSize: 34,
    color: '#0F172A',
    letterSpacing: -0.8,
  },
  heroMeta: {
    marginTop: 4,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1EAE3',
  },
  footerCell: { flex: 1, alignItems: 'center' },
  footerRule: { width: 1, height: 28, backgroundColor: '#E2E8F0' },
  footerValue: { fontFamily: fonts.bold, fontSize: 16, color: '#0F172A' },
  footerLabel: {
    marginTop: 3,
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#64748B',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EFE6DF',
    overflow: 'hidden',
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
  },
  cardTitle: { fontFamily: fonts.bold, fontSize: 15, color: '#0F172A' },
  cardAside: { fontFamily: fonts.semiBold, fontSize: 12, color: authTheme.brand },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  cell: {
    width: '50%',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#F1EAE3',
    gap: 2,
  },
  cellRight: { borderLeftWidth: 1, borderLeftColor: '#F1EAE3' },
  cellValue: {
    fontFamily: fonts.extraBold,
    fontSize: 20,
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  cellLabel: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: '#64748B',
  },
  chartBody: { paddingHorizontal: 12, paddingBottom: 14 },
  chartScroll: { flexGrow: 0 },
  barsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 132,
    gap: 4,
  },
  barCol: { flex: 1, alignItems: 'center', height: '100%', justifyContent: 'flex-end' },
  barTrack: {
    width: 18,
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  barFill: {
    width: 18,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: '#F6C7B0',
  },
  barFillPeak: { backgroundColor: authTheme.brand },
  barLabel: {
    fontFamily: fonts.medium,
    fontSize: 10,
    color: '#94A3B8',
  },
  barLabelPeak: { fontFamily: fonts.bold, color: authTheme.brand },
  empty: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#94A3B8',
    textAlign: 'center',
    paddingVertical: 22,
  },
});
