import { StyleSheet } from 'react-native';

import { fonts } from '@/constants/typography';

export const analyticsPageStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F6F3F0' },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 8,
    gap: 14,
  },
  title: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  sub: {
    marginTop: -8,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  period: {
    flexDirection: 'row',
    backgroundColor: '#EFE8E2',
    borderRadius: 14,
    padding: 4,
  },
  periodBtn: {
    flex: 1,
    minHeight: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  periodBtnOn: { backgroundColor: '#FFFFFF' },
  periodText: { fontFamily: fonts.medium, fontSize: 13, color: '#64748B' },
  periodTextOn: { fontFamily: fonts.bold, color: '#0F172A' },
  scroll: { paddingHorizontal: 16, paddingTop: 8, gap: 12 },
  center: { paddingVertical: 48, alignItems: 'center', gap: 10 },
  errorText: {
    fontFamily: fonts.medium,
    fontSize: 14,
    color: '#B91C1C',
    textAlign: 'center',
  },
  retry: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F1EAE3',
  },
  retryText: { fontFamily: fonts.semiBold, fontSize: 13, color: '#0F172A' },
  hero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    padding: 18,
    gap: 14,
  },
  heroKicker: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#EA4B14',
    letterSpacing: 0.6,
  },
  heroAmount: {
    fontFamily: fonts.extraBold,
    fontSize: 34,
    color: '#0F172A',
    letterSpacing: -0.8,
    marginTop: 2,
  },
  heroMeta: { fontFamily: fonts.medium, fontSize: 13, color: '#64748B' },
  split: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#F1EAE3',
    paddingTop: 14,
  },
  splitCol: { flex: 1, gap: 2 },
  splitRule: { width: 1, backgroundColor: '#E7E0DA', marginHorizontal: 14 },
  splitLabel: { fontFamily: fonts.medium, fontSize: 12, color: '#64748B' },
  splitValue: { fontFamily: fonts.bold, fontSize: 16, color: '#0F172A' },
  sectionLabel: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: '#0F172A',
    marginTop: 4,
    marginLeft: 4,
  },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  stat: {
    width: '48%',
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 4,
    minWidth: 140,
  },
  statValue: {
    fontFamily: fonts.extraBold,
    fontSize: 22,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  statLabel: { fontFamily: fonts.semiBold, fontSize: 13, color: '#0F172A' },
  statHint: { fontFamily: fonts.medium, fontSize: 12, color: '#94A3B8' },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    padding: 16,
    gap: 14,
  },
  cardTitle: { fontFamily: fonts.bold, fontSize: 15, color: '#0F172A' },
  cardHint: { fontFamily: fonts.medium, fontSize: 12, color: '#94A3B8', marginTop: -8 },
  barsRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, height: 120 },
  barCol: { flex: 1, alignItems: 'center', gap: 6 },
  barTrack: {
    flex: 1,
    width: '70%',
    maxWidth: 22,
    justifyContent: 'flex-end',
    backgroundColor: '#F6F3F0',
    borderRadius: 8,
    overflow: 'hidden',
  },
  barFill: { width: '100%', backgroundColor: '#EA4B14', borderRadius: 8 },
  barLabel: {
    fontFamily: fonts.medium,
    fontSize: 10,
    color: '#94A3B8',
    textAlign: 'center',
  },
  empty: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#94A3B8',
    textAlign: 'center',
    paddingVertical: 18,
  },
});
