import { StyleSheet } from 'react-native';

import { authTheme, PARTNER_BOTTOM_NAV_INSET } from '@/constants/auth-theme';
import { fonts } from '@/constants/typography';

export const onboardingStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: authTheme.surface },
  scroll: { flex: 1 },
  content: {
    paddingHorizontal: 16,
    paddingBottom: PARTNER_BOTTOM_NAV_INSET,
    gap: 12,
  },
  hero: {
    flexDirection: 'row',
    gap: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: authTheme.cardBorder,
    padding: 14,
    alignItems: 'center',
  },
  percentWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: authTheme.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  percent: {
    color: authTheme.brand,
    fontFamily: fonts.extraBold,
    fontSize: 18,
  },
  percentLabel: {
    color: authTheme.textMuted,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  heroTitle: {
    color: authTheme.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  heroSub: {
    color: authTheme.textMuted,
    fontFamily: fonts.medium,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  chip: {
    alignSelf: 'flex-start',
    marginTop: 8,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipText: { fontFamily: fonts.bold, fontSize: 11 },
  trackRow: { flexDirection: 'row', gap: 8 },
  track: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  trackFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: authTheme.brand,
  },
  rejectBox: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    padding: 12,
  },
  rejectText: {
    flex: 1,
    color: '#B91C1C',
    fontFamily: fonts.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  waitBox: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 12,
  },
  waitText: {
    flex: 1,
    color: '#92400E',
    fontFamily: fonts.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  liveBox: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    backgroundColor: '#F0FDF4',
    borderRadius: 12,
    padding: 12,
  },
  liveText: {
    flex: 1,
    color: '#166534',
    fontFamily: fonts.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  sectionLabel: {
    fontFamily: fonts.bold,
    fontSize: 13,
    color: authTheme.textMuted,
    marginTop: 4,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: authTheme.cardBorder,
    paddingHorizontal: 12,
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: authTheme.cardBorder,
    padding: 14,
    gap: 10,
  },
  formCardNested: {
    marginHorizontal: 4,
    marginBottom: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: authTheme.cardBorder,
    padding: 12,
    gap: 10,
  },
  formTitle: {
    fontFamily: fonts.bold,
    fontSize: 15,
    color: authTheme.text,
  },
  formHint: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: authTheme.textMuted,
    lineHeight: 17,
  },
  muted: {
    marginTop: 24,
    textAlign: 'center',
    fontFamily: fonts.medium,
    color: authTheme.textMuted,
  },
  error: {
    marginTop: 24,
    textAlign: 'center',
    fontFamily: fonts.medium,
    color: authTheme.error,
  },
  idChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  idChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F1F5F9',
  },
  idChipOn: { backgroundColor: authTheme.brandSoft },
  idChipText: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: authTheme.textMuted,
  },
  idChipTextOn: { color: authTheme.brand },
});
