import { StyleSheet } from 'react-native';

import { theme } from '@/constants/theme';

export const locationMapPickerStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FFFFFF' },
  mapPane: { flex: 1, backgroundColor: '#E8EAED', position: 'relative' },
  map: { flex: 1, width: '100%', backgroundColor: '#E8EAED' },
  mapLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#E8EAED',
  },
  mapLoadingText: {
    fontSize: 14,
    color: theme.secondaryLight,
    fontWeight: '600',
  },
  mapFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    gap: 10,
    backgroundColor: theme.surface,
  },
  mapFallbackTitle: {
    color: theme.secondary,
    fontWeight: '800',
    fontSize: 16,
    textAlign: 'center',
  },
  mapFallbackText: {
    color: theme.secondaryLight,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  topSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    elevation: 20,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
  },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 48,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  searchInput: { flex: 1, fontSize: 15, color: theme.secondary },
  closeBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  currentLocationCard: {
    marginTop: 10,
    marginHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  currentLocationIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  currentLocationTitle: {
    color: theme.secondary,
    fontWeight: '800',
    fontSize: 14,
  },
  currentLocationSub: {
    color: theme.secondaryLight,
    fontSize: 12,
    marginTop: 2,
  },
  searchingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  searchingText: {
    color: theme.secondaryLight,
    fontWeight: '600',
    fontSize: 13,
  },
  searchErrorInline: {
    fontSize: 13,
    color: theme.danger,
    fontWeight: '500',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  suggestions: {
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 16,
    maxHeight: 340,
    zIndex: 50,
  },
  suggestionsScroll: { maxHeight: 340 },
  poweredBy: {
    textAlign: 'center',
    fontSize: 11,
    color: theme.secondaryLight,
    fontWeight: '500',
    paddingVertical: 10,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  suggestionRowLast: { borderBottomWidth: 0 },
  suggestionIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  suggestionMain: { color: '#0F172A', fontWeight: '700', fontSize: 14 },
  suggestionSecondary: {
    color: '#64748B',
    fontSize: 12,
    marginTop: 2,
    lineHeight: 16,
  },
  bottomPanel: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E5E7EB',
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  detectedRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  detectedLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    color: theme.secondaryLight,
  },
  detectedValue: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: '600',
    color: theme.secondary,
  },
  detectedHint: { marginTop: 2, fontSize: 12, color: theme.muted },
  errorText: {
    fontSize: 13,
    color: theme.danger,
    fontWeight: '500',
    marginBottom: 8,
  },
});
