import { StyleSheet } from 'react-native';

import { authTheme } from '@/constants/auth-theme';
import { fonts } from '@/constants/typography';

export const profilePageStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F6F3F0' },
  scroll: { paddingHorizontal: 16, gap: 12 },
  pageTitle: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  pageSub: {
    marginTop: -6,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  center: { paddingVertical: 48, alignItems: 'center', gap: 10 },
  muted: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
  },
  banner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    padding: 16,
    gap: 8,
  },
  bannerTitle: { fontFamily: fonts.semiBold, fontSize: 15, color: '#0F172A' },
  retryBtn: {
    alignSelf: 'flex-start',
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: authTheme.brand,
  },
  retryText: { fontFamily: fonts.semiBold, fontSize: 13, color: '#FFFFFF' },
  hero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    padding: 16,
  },
  identity: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatarWrap: { width: 72, height: 72 },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#FFF1E8',
  },
  avatarFallback: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: authTheme.brand,
  },
  avatarInitials: { fontFamily: fonts.bold, fontSize: 24, color: '#FFFFFF' },
  cameraBtn: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: authTheme.brand,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  identityBody: { flex: 1, minWidth: 0 },
  name: { fontFamily: fonts.bold, fontSize: 20, color: '#0F172A' },
  meta: {
    marginTop: 4,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  pill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  pillText: { fontFamily: fonts.semiBold, fontSize: 11 },
  performanceDivider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginTop: 16,
  },
  stats: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 14,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#E2E8F0',
  },
  stat: { flex: 1, alignItems: 'center' },
  statValue: { fontFamily: fonts.bold, fontSize: 17, color: '#0F172A' },
  statLabel: {
    marginTop: 3,
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#94A3B8',
  },
  kyc: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF7F2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  kycText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 12,
    color: '#9A3412',
    marginRight: 8,
  },
  kycLink: { fontFamily: fonts.bold, fontSize: 12, color: authTheme.brand },
  groupLabel: {
    marginTop: 6,
    marginBottom: -4,
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#94A3B8',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    paddingHorizontal: 14,
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 14,
    paddingBottom: 4,
  },
  cardTitle: { fontFamily: fonts.bold, fontSize: 15, color: '#0F172A' },
  edit: { fontFamily: fonts.bold, fontSize: 13, color: authTheme.brand },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 52,
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#F4EEE8',
  },
  rowFirst: { borderTopWidth: 0 },
  rowLabel: { width: 78, fontFamily: fonts.medium, fontSize: 13, color: '#94A3B8' },
  rowValue: {
    flex: 1,
    fontFamily: fonts.semiBold,
    fontSize: 14,
    color: '#1E293B',
  },
  rowAction: { fontFamily: fonts.bold, fontSize: 13, color: authTheme.brand },
  vehicleLine: {
    paddingBottom: 14,
    fontFamily: fonts.semiBold,
    fontSize: 15,
    color: '#1E293B',
  },
  vehicleMeta: {
    marginTop: 2,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  secureBody: { flex: 1, minWidth: 0 },
  secureTitle: { fontFamily: fonts.semiBold, fontSize: 14, color: '#0F172A' },
  secureHint: { marginTop: 2, fontFamily: fonts.medium, fontSize: 12, color: '#64748B' },
  logout: {
    marginTop: 8,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutText: { fontFamily: fonts.bold, fontSize: 15, color: authTheme.error },
});
