import { StyleSheet } from 'react-native';

import { authTheme } from '@/constants/auth-theme';
import { fonts } from '@/constants/typography';

export const profilePageStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F6F3F0' },
  scroll: { paddingHorizontal: 16, gap: 12 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  pageTitle: {
    fontFamily: fonts.bold,
    fontSize: 28,
    color: '#0F172A',
    letterSpacing: -0.4,
  },
  pageSub: {
    marginTop: 6,
    marginBottom: 16,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  center: { paddingVertical: 48, alignItems: 'center', gap: 10 },
  muted: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
  },
  banner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    padding: 16,
    gap: 8,
  },
  bannerTitle: { fontFamily: fonts.semiBold, fontSize: 15, color: '#0F172A' },
  retryBtn: {
    alignSelf: 'flex-start',
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: authTheme.brand,
  },
  retryText: { fontFamily: fonts.semiBold, fontSize: 13, color: '#FFFFFF' },
  hero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#EFE6DF',
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  idBand: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: authTheme.brand,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  idBrand: {
    fontFamily: fonts.extraBold,
    fontSize: 15,
    color: '#FFFFFF',
    letterSpacing: 1.6,
  },
  idRole: {
    fontFamily: fonts.semiBold,
    fontSize: 11,
    color: '#FFFFFF',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  identity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 4,
  },
  avatarWrap: { width: 84, height: 100 },
  avatar: {
    width: 84,
    height: 100,
    borderRadius: 14,
    backgroundColor: '#FFF1E8',
    borderWidth: 1,
    borderColor: '#F1EAE3',
  },
  avatarFallback: {
    width: 84,
    height: 100,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF1E8',
  },
  avatarInitials: { fontFamily: fonts.extraBold, fontSize: 28, color: authTheme.brand },
  cameraBtn: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: authTheme.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  identityBody: { flex: 1, minWidth: 0 },
  name: { fontFamily: fonts.extraBold, fontSize: 22, color: '#0F172A', letterSpacing: -0.3 },
  idKicker: {
    marginTop: 8,
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#94A3B8',
    letterSpacing: 0.3,
  },
  idCode: {
    marginTop: 1,
    fontFamily: fonts.bold,
    fontSize: 15,
    color: '#1E293B',
    letterSpacing: 1.2,
  },
  statusLine: { flexDirection: 'row', alignItems: 'center', marginTop: 10, gap: 6 },
  statusDot: { width: 7, height: 7, borderRadius: 4 },
  statusText: { fontFamily: fonts.semiBold, fontSize: 12, color: '#475569' },
  statusSep: { fontFamily: fonts.medium, fontSize: 12, color: '#CBD5E1' },
  performanceDivider: {
    height: 1,
    backgroundColor: '#F1EAE3',
    marginTop: 16,
  },
  stats: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FBF8F6',
    paddingVertical: 14,
    paddingHorizontal: 8,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#E2E8F0',
  },
  stat: { flex: 1, alignItems: 'center' },
  statValue: { fontFamily: fonts.bold, fontSize: 17, color: '#0F172A' },
  statLabel: {
    marginTop: 3,
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#94A3B8',
  },
  kyc: {
    marginTop: 12,
    marginHorizontal: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF7F2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  kycText: {
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 12,
    color: '#9A3412',
    marginRight: 8,
  },
  kycLink: { fontFamily: fonts.bold, fontSize: 12, color: authTheme.brand },
  groupLabel: {
    marginTop: 6,
    marginBottom: -4,
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#94A3B8',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    paddingHorizontal: 14,
  },
  cardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 14,
    paddingBottom: 4,
  },
  cardTitle: { fontFamily: fonts.bold, fontSize: 15, color: '#0F172A' },
  edit: { fontFamily: fonts.bold, fontSize: 13, color: authTheme.brand },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 52,
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#F4EEE8',
  },
  rowFirst: { borderTopWidth: 0 },
  rowLabel: { width: 78, fontFamily: fonts.medium, fontSize: 13, color: '#94A3B8' },
  rowValue: {
    flex: 1,
    fontFamily: fonts.semiBold,
    fontSize: 14,
    color: '#1E293B',
  },
  rowAction: { fontFamily: fonts.bold, fontSize: 12, color: authTheme.brand },
  vehicleLine: {
    paddingBottom: 14,
    fontFamily: fonts.semiBold,
    fontSize: 15,
    color: '#1E293B',
  },
  vehicleMeta: {
    marginTop: 2,
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#64748B',
  },
  secureBody: { flex: 1, minWidth: 0 },
  secureTitle: { fontFamily: fonts.semiBold, fontSize: 14, color: '#0F172A' },
  secureHint: { marginTop: 2, fontFamily: fonts.medium, fontSize: 12, color: '#64748B' },
  logout: {
    marginTop: 4,
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1EAE3',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  logoutText: { fontFamily: fonts.semiBold, fontSize: 15, color: '#B91C1C' },
});
